spring:
  application:
    name: ms-habilidades
  datasource:
    url: jdbc:mysql://localhost:3306/portafolio
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
        format_sql: true

server:
  port: 9093